export const ERROR_CODES = {
  // AUTH
  AUTH_MISSING_CREDENTIALS: 'AUTH_001',
  AUTH_INVALID_CREDENTIALS: 'AUTH_002',
  AUTH_TOKEN_MISSING: 'AUTH_003',
  AUTH_TOKEN_INVALID: 'AUTH_004',

  // USER
  USER_NOT_FOUND: 'USER_001',
  USER_ALREADY_EXISTS: 'USER_002',
  USER_FORBIDDEN: 'USER_003',

  // MENU
  MENU_NOT_FOUND: 'MENU_001',
  MENU_NOT_ACTIVE: 'MENU_002',
  MENU_INVALID_PAYLOAD: 'MENU_003', 

  // ORDER TYPE
  ORDER_TYPE_INVALID: 'ORDER_TYPE_001',
  ORDER_TYPE_PAYMENT_REQUIRED: 'ORDER_TYPE_402', 
  ORDER_TYPE_REQUIRED: 'ORDER_TYPE_002',
  ORDER_TYPE_INVALID_PAYLOAD: 'ORDER_TYPE_003',

  // COMMON
  VALIDATION_ERROR: 'COMMON_001',
  INTERNAL_ERROR: 'COMMON_500',

  //ITEM
    INVALID_ID: 'ITEM_001',
    INVALID_PAYLOAD: 'ITEM_002',
    INVALID_AVAILABILITY: 'ITEM_003',
    NOT_FOUND: 'ITEM_004',
  
} as const;
